x-depends-on: &depends-on
  - postgres
  - redis

x-superset-volumes: &superset-volumes
  - superset_home:/app/superset_home
  - ../superset/dashboards_images:/app/superset/static/assets/dashboards_images
x-superset-environment: &superset-environment
  CYPRESS_CONFIG: "false"
  DATABASE_DB: ${POSTGRES_SUPERSET_DB}
  DATABASE_DIALECT: postgresql
  DATABASE_HOST: postgres
  DATABASE_PASSWORD: ${POSTGRES_SUPERSET_PASSWORD}
  DATABASE_PORT: 5432
  DATABASE_USER: ${POSTGRES_SUPERSET_USER}
  FLASK_ENV: production
  MAPBOX_API_KEY: ${SUPERSET_MAPBOX_API_KEY}
  PYTHONPATH: /app/pythonpath:/app/pythonpath_docker
  REDIS_CELERY_DB: 4
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_RESULTS_DB: 3
  SECRET_KEY: $SUPERSET_SECRET_KEY
  SUPERSET_ENV: production

x-dashboard-environment: &dashboard-environment
  POSTGRES_DEFAULT_HOST: postgres
  POSTGRES_DEFAULT_PORT: 5432
  POSTGRES_DEFAULT_USER: ${POSTGRES_DASHBOARD_VIEWER_USER}
  POSTGRES_DEFAULT_PASSWORD: ${POSTGRES_DASHBOARD_VIEWER_PASSWORD}
  POSTGRES_DEFAULT_DB: ${POSTGRES_DASHBOARD_VIEWER_DB}
  POSTGRES_ACHILLES_HOST: postgres
  POSTGRES_ACHILLES_PORT: 5432
  POSTGRES_ACHILLES_USER: ${POSTGRES_ACHILLES_USER}
  POSTGRES_ACHILLES_PASSWORD: ${POSTGRES_ACHILLES_PASSWORD}
  POSTGRES_ACHILLES_DB: ${POSTGRES_ACHILLES_DB}
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_CACHE_DB: 0
  REDIS_CELERY_DB: 1
  REDIS_CONSTANCE_DB: 2
  SECRET_KEY: ${DASHBOARD_VIEWER_SECRET_KEY}
  DASHBOARD_VIEWER_ENV: ${INSTALLATION_ENV}
  SINGLE_APPLICATION_MODE: ${SINGLE_APPLICATION_MODE}
  MAIN_APPLICATION_HOST: ${MAIN_APPLICATION_HOST}

version: "3.7"
services:
  #### SUPERSET ####
  superset:
    image: ehdenavr/networkdashboards_superset
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    restart: unless-stopped
    environment: *superset-environment
    user: "root"
    depends_on: *depends-on
    volumes: *superset-volumes
    ports:
      - ${SUPERSET_PORT}:8088

  superset-init:
    image: ehdenavr/networkdashboards_superset
    command: ["/app/docker/docker-init.sh"]
    environment: *superset-environment
    user: "root"
    depends_on: *depends-on
    volumes: *superset-volumes

  superset-worker:
    image: ehdenavr/networkdashboards_superset
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    restart: unless-stopped
    environment: *superset-environment
    user: "root"
    depends_on: *depends-on
    volumes: *superset-volumes

  superset-worker-beat:
    image: ehdenavr/networkdashboards_superset
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    restart: unless-stopped
    environment: *superset-environment
    user: "root"
    depends_on: *depends-on
    volumes: *superset-volumes

  #### DATA ####
  redis:
    image: redis:3.2
    restart: unless-stopped
    volumes:
      - ${VOLUMES_PATH}/redis:/data

  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      # Variables below are used to iniliaze databases for the
      #  services below (superset and dashboard_viewer).
      POSTGRES_DBS: ${POSTGRES_SUPERSET_DB} ${POSTGRES_DASHBOARD_VIEWER_DB} ${POSTGRES_ACHILLES_DB}
      POSTGRES_DBS_USERS: ${POSTGRES_SUPERSET_USER} ${POSTGRES_DASHBOARD_VIEWER_USER} ${POSTGRES_ACHILLES_USER}
      POSTGRES_DBS_PASSWORDS: ${POSTGRES_SUPERSET_PASSWORD} ${POSTGRES_DASHBOARD_VIEWER_PASSWORD} ${POSTGRES_ACHILLES_PASSWORD}
    volumes:
      - ${VOLUMES_PATH}/postgres:/var/lib/postgresql/data
      - ./postgres-entrypoint:/docker-entrypoint-initdb.d

  #### DASHBOARD ####
  nginx:
    image: nginx:1.18.0
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - dashboard_static:/static/dashboard
      - ../dashboard_viewer/media:/media
    depends_on:
      - dashboard

  dashboard_worker:
    image: ehdenavr/networkdashboards
    environment: *dashboard-environment
    command: celery -A dashboard_viewer worker -Ofair -l INFO
    restart: unless-stopped
    depends_on: *depends-on
    volumes:
      - ../dashboard_viewer/media:/app/media

  dashboard:
    image: ehdenavr/networkdashboards
    environment: *dashboard-environment
    depends_on: *depends-on
    restart: unless-stopped
    volumes:
      - dashboard_static:/app/static
      - ../dashboard_viewer/media:/app/media

volumes:
  superset_home:
  dashboard_static:
