version: "3"
services:
  redis:
    image: redis:3.2
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/data

  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_ROOT_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_ROOT_PASSWORD}"
      # Variables below are used to iniliaze databases for the
      #  services below (superset and dashboard_viewer).
      POSTGRES_DBS: "${POSTGRES_SUPERSET_DB} ${POSTGRES_DASHBOARD_VIEWER_DB} ${POSTGRES_ACHILLES_DB}"
      POSTGRES_DBS_USERS: "${POSTGRES_SUPERSET_USER} ${POSTGRES_DASHBOARD_VIEWER_USER} ${POSTGRES_ACHILLES_USER}"
      POSTGRES_DBS_PASSWORDS: "${POSTGRES_SUPERSET_PASSWORD} ${POSTGRES_DASHBOARD_VIEWER_PASSWORD} ${POSTGRES_ACHILLES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres-entrypoint:/docker-entrypoint-initdb.d

  superset:
    build:
      context: ../superset
      dockerfile: contrib/docker/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: "${POSTGRES_SUPERSET_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_SUPERSET_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_SUPERSET_DB}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # If using production, comment development volume below
      #SUPERSET_ENV: production
      SUPERSET_ENV: development
    user: root:root
    ports:
      - "${SUPERSET_PORT}:8088"
    depends_on:
      - postgres
      - redis
    volumes:
      # this is needed to communicate with the postgres and redis services
      - ../superset/superset_config.py:/home/superset/superset/superset_config.py
      # this is needed for development, remove with SUPERSET_ENV=production
      - ../../superset:/home/superset/superset

  dashboard_viewer:
    build:
      context: ../dashboard_viewer
    environment:
      POSTGRES_DEFAULT_HOST: postgres
      POSTGRES_DEFAULT_PORT: 5432
      POSTGRES_DEFAULT_USER: "${POSTGRES_DASHBOARD_VIEWER_USER}"
      POSTGRES_DEFAULT_PASSWORD: "${POSTGRES_DASHBOARD_VIEWER_PASSWORD}"
      POSTGRES_DEFAULT_DB: "${POSTGRES_DASHBOARD_VIEWER_DB}"
      POSTGRES_ACHILLES_HOST: postgres
      POSTGRES_ACHILLES_PORT: 5432
      POSTGRES_ACHILLES_USER: "${POSTGRES_ACHILLES_USER}"
      POSTGRES_ACHILLES_PASSWORD: "${POSTGRES_ACHILLES_PASSWORD}"
      POSTGRES_ACHILLES_DB: "${POSTGRES_ACHILLES_DB}"
      # If using production, comment development volume below
      #DASHBOARD_VIEWER_ENV: production
      DASHBOARD_VIEWER_ENV: development
    ports:
      - "${DASHBOARD_VIEWER_PORT}:8000"
    depends_on:
      - postgres
    volumes:
      # this is needed for development, remove with DASHBOARD_VIEWER_ENV=production
      - ../dashboard_viewer:/app

volumes:
  postgres:
    external: false
  redis:
    external: false
