# Generated by Django 3.2.13 on 2024-03-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0013_auto_20210721_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnBoardingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # just set a dummy folder, because this model will be deleted anyway in a following migration
                ('uploaded_file', models.FileField(null=True, upload_to="onboarding/")),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.datasource')),
            ],
            options={
                'db_table': 'onboarding_report',
            },
        ),
    ]
