# Generated by Django 3.2.13 on 2024-03-28 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0014_onboardingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingreport',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
