# Generated by Django 3.2.13 on 2025-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0015_onboardingreport_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='database_type',
            field=models.CharField(help_text='Type of the data source.', max_length=100),
        ),
    ]
