# Generated by Django 3.2.13 on 2026-05-04 16:53

from django.db import migrations, models
import django.db.models.deletion
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0016_alter_datasource_database_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to=uploader.models.get_report_upload_path)),
                ('report_type', models.CharField(choices=[('OB', 'Onboarding Report'), ('AB', 'Analytical Benchmark'), ('PN', 'PeriNet study')], default='OB', max_length=3)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.datasource')),
            ],
            options={
                'db_table': 'data_report',
                'get_latest_by': 'upload_date',
            },
        ),
    ]
