# Generated by Django 3.2.13 on 2026-05-04 16:58

from django.db import migrations

def migrate_onboarding_data(apps, schema_editor):
    # Retrieve models via the 'apps' registry to avoid direct imports
    OnboardingReport = apps.get_model('uploader', 'OnboardingReport')
    DataReport = apps.get_model('uploader', 'DataReport')

    for old_obj in OnboardingReport.objects.all():
        # Create a new DataReport entry for every old Onboarding entry
        DataReport.objects.create(
            data_source=old_obj.data_source,
            uploaded_file=old_obj.uploaded_file,
            report_type='OB',
            upload_date=old_obj.upload_date 
        )

def reverse_migration(apps, schema_editor):
    DataReport = apps.get_model('uploader', 'DataReport')
    DataReport.objects.filter(report_type='ONB').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0017_datareport'),
    ]

    operations = [
        migrations.RunPython(migrate_onboarding_data, reverse_migration),
    ]