# Generated by Django 3.2.13 on 2026-05-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0018_migrate_onboardingreports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnBoardingReport',
        ),
    ]
