# Generated by Django 3.2.13 on 2026-05-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0019_delete_onboardingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='internal_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
