name: Django

on:
  pull_request:
    branches: [ dev ]

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: black
      run: black --check $(echo $PYTHON_LINT_TARGET)
    - name: mypy
      run: mypy $(echo $PYTHON_LINT_TARGET)
    - name: isort
      run: isort --check-only --recursive $(echo $PYTHON_LINT_TARGET)
    - name: pylint
      # `-j 0` run Pylint in parallel
      run: pylint -j 0 superset
