name: Build & Publish Docker Images

on:
  release:
    types: [published]

jobs:
  dashboards:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aspedrosa/networkdashboards
          tags: |
              type=pep440,pattern={{version}}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: dashboard_viewer
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  superset:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aspedrosa/networkdashboards_superset
          tags: |
              type=pep440,pattern={{version}}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: superset
          file: "{context}/../docker/superset/Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
